##
# @file self_defined_errors.py
# @synopsis  Self defined errors to be consistent and reader-friendly
# @author Ren Miaojian
# @version 0.1
# @date 2018-03-09


HTTP_1000_PARAM_FORMAT_ERROR = 520
HTTP_1001_CMDB_INSERT_KEY_DUPLICATE = 521
HTTP_2000_PALLAS_CR_ERROR = 523
HTTP_2001_PALLAS_CR_PLAN_ERROR = 524
HTTP_2002_PALLAS_CR_TASK_ERROR = 525
HTTP_535_PALLAS_CR_LOCK_FAILED = 535
HTTP_2003_PALLAS_CR_ARRANGEMENT_APPROVE_ERROR = 526
HTTP_2100_PALLAS_NA_ERROR = 527
HTTP_2101_PALLAS_NA_EXEC_ERROR = 528
HTTP_2102_PALLAS_NA_CREATE_ERROR = 529
HTTP_2103_PALLAS_NA_CALLBACK = 530
HTTP_2200_PALLAS_CMDB_ERROR = 531
HTTP_2201_PALLAS_CMDB_NA_ERROR = 532
HTTP_2202_PALLAS_CMDB_ROLLBACK_CHECK_ERROR = 533
HTTP_2300_PALLAS_VC_ERROR = 534
HTTP_2400_HEALTH_CHECK_ERROR = 550

# --------------------------------------------------------------------------
##
# @synopsis  ERROR code starts from 1000 to extend default HTTP code
# ----------------------------------------------------------------------------
SELF_DEFINED_ERROR_DICT = {

    HTTP_1000_PARAM_FORMAT_ERROR: 'INPUT PARAM FORMAT ERROR',
    HTTP_1001_CMDB_INSERT_KEY_DUPLICATE: 'CMDB INSERT FAIL DUE TO DUPLICATE KEY',

    # pallas change record
    HTTP_2000_PALLAS_CR_ERROR: 'PALLAS CHANGE RECORD ERROR',
    HTTP_2001_PALLAS_CR_PLAN_ERROR: 'PALLAS CHANGE RECORD PLAN ERROR',
    HTTP_2002_PALLAS_CR_TASK_ERROR: 'PALLAS CHANGE RECORD TASK ERROR',
    HTTP_2003_PALLAS_CR_ARRANGEMENT_APPROVE_ERROR: 'PALLAS CHANGE RECORD ARRANGEMENT APPROVE ERROR',
    HTTP_535_PALLAS_CR_LOCK_FAILED: 'PALLAS CHANGE RECORD LOCK FAILED',

    # pallas nginx admin
    HTTP_2100_PALLAS_NA_ERROR: 'PALLAS NGINX ADMIN ERROR',
    HTTP_2101_PALLAS_NA_EXEC_ERROR: 'PALLAS NGINX ADMIN EXEC ERROR',
    HTTP_2102_PALLAS_NA_CREATE_ERROR: 'PALLAS NGINX ADMIN CREATE ERROR',
    HTTP_2103_PALLAS_NA_CALLBACK: 'PALLAS NGINX ADMIN CALLBACK ERROR',

    # pallas cmdb na:nginx_admin
    HTTP_2200_PALLAS_CMDB_ERROR: 'PALLAS CMDB ERROR',
    HTTP_2201_PALLAS_CMDB_NA_ERROR: 'PALLAS CMDB NGINX ADMIN ERROR',
    HTTP_2202_PALLAS_CMDB_ROLLBACK_CHECK_ERROR: 'PALLAS CMDB ROLLBACK CHECK ERROR',

    # pallas cmdb vc
    HTTP_2300_PALLAS_VC_ERROR: 'PALLAS VC ERROR',

    # health check
    HTTP_2400_HEALTH_CHECK_ERROR: 'PALLAS HEALTH CHECK ERROR'
}


ERROR_MSG_DELIMITER = '---->\n'
