# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_service.proto',
  package='DataService',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x64\x61ta_service.proto\x12\x0b\x44\x61taService\"P\n\x12\x44\x61taServiceRequest\x12\x10\n\x08sequence\x18\x01 \x01(\t\x12\x13\n\x0bservicetype\x18\x02 \x01(\t\x12\x13\n\x0bjson_string\x18\x03 \x01(\t\"h\n\x13\x44\x61taServiceResponse\x12\x10\n\x08sequence\x18\x01 \x01(\t\x12\x13\n\x0bservicetype\x18\x02 \x01(\t\x12\x15\n\rhandle_result\x18\x03 \x01(\t\x12\x13\n\x0bjson_string\x18\x04 \x01(\t2u\n\x14\x44\x61taServiceRequester\x12]\n\x16SendDataServiceRequest\x12\x1f.DataService.DataServiceRequest\x1a .DataService.DataServiceResponse\"\x00\x62\x06proto3')
)




_DATASERVICEREQUEST = _descriptor.Descriptor(
  name='DataServiceRequest',
  full_name='DataService.DataServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='DataService.DataServiceRequest.sequence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servicetype', full_name='DataService.DataServiceRequest.servicetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='json_string', full_name='DataService.DataServiceRequest.json_string', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=115,
)


_DATASERVICERESPONSE = _descriptor.Descriptor(
  name='DataServiceResponse',
  full_name='DataService.DataServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='DataService.DataServiceResponse.sequence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servicetype', full_name='DataService.DataServiceResponse.servicetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='handle_result', full_name='DataService.DataServiceResponse.handle_result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='json_string', full_name='DataService.DataServiceResponse.json_string', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['DataServiceRequest'] = _DATASERVICEREQUEST
DESCRIPTOR.message_types_by_name['DataServiceResponse'] = _DATASERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataServiceRequest = _reflection.GeneratedProtocolMessageType('DataServiceRequest', (_message.Message,), dict(
  DESCRIPTOR = _DATASERVICEREQUEST,
  __module__ = 'data_service_pb2'
  # @@protoc_insertion_point(class_scope:DataService.DataServiceRequest)
  ))
_sym_db.RegisterMessage(DataServiceRequest)

DataServiceResponse = _reflection.GeneratedProtocolMessageType('DataServiceResponse', (_message.Message,), dict(
  DESCRIPTOR = _DATASERVICERESPONSE,
  __module__ = 'data_service_pb2'
  # @@protoc_insertion_point(class_scope:DataService.DataServiceResponse)
  ))
_sym_db.RegisterMessage(DataServiceResponse)



_DATASERVICEREQUESTER = _descriptor.ServiceDescriptor(
  name='DataServiceRequester',
  full_name='DataService.DataServiceRequester',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=223,
  serialized_end=340,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendDataServiceRequest',
    full_name='DataService.DataServiceRequester.SendDataServiceRequest',
    index=0,
    containing_service=None,
    input_type=_DATASERVICEREQUEST,
    output_type=_DATASERVICERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASERVICEREQUESTER)

DESCRIPTOR.services_by_name['DataServiceRequester'] = _DATASERVICEREQUESTER

# @@protoc_insertion_point(module_scope)
