# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oracle_sql_predict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oracle_sql_predict.proto',
  package='OracleSQLPredict',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18oracle_sql_predict.proto\x12\x10OracleSQLPredict\"\xbb\x01\n\x17OracleSQLPredictRequest\x12\x14\n\x0crpc_sequence\x18\x01 \x01(\t\x12\x14\n\x0csql_sequence\x18\x02 \x01(\t\x12\x0e\n\x06userid\x18\x03 \x01(\t\x12\x0e\n\x06tenant\x18\x04 \x01(\t\x12\x14\n\x0cprofile_name\x18\x05 \x01(\t\x12\x0e\n\x06schema\x18\x06 \x01(\t\x12\x10\n\x08sql_text\x18\x07 \x01(\t\x12\x1c\n\x14\x61\x64\x64ition_json_string\x18\x08 \x01(\t\"\x88\x01\n\x18OracleSQLPredictResponse\x12\x14\n\x0crpc_sequence\x18\x01 \x01(\t\x12\x11\n\tai_result\x18\x02 \x01(\t\x12\x14\n\x0c\x61i_recommend\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x1c\n\x14\x61\x64\x64ition_json_string\x18\n \x01(\t2\x82\x01\n\x19OracleSQLPredictRequester\x12\x65\n\nSQLPredict\x12).OracleSQLPredict.OracleSQLPredictRequest\x1a*.OracleSQLPredict.OracleSQLPredictResponse\"\x00\x62\x06proto3')
)




_ORACLESQLPREDICTREQUEST = _descriptor.Descriptor(
  name='OracleSQLPredictRequest',
  full_name='OracleSQLPredict.OracleSQLPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpc_sequence', full_name='OracleSQLPredict.OracleSQLPredictRequest.rpc_sequence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sql_sequence', full_name='OracleSQLPredict.OracleSQLPredictRequest.sql_sequence', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userid', full_name='OracleSQLPredict.OracleSQLPredictRequest.userid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenant', full_name='OracleSQLPredict.OracleSQLPredictRequest.tenant', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='OracleSQLPredict.OracleSQLPredictRequest.profile_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='OracleSQLPredict.OracleSQLPredictRequest.schema', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sql_text', full_name='OracleSQLPredict.OracleSQLPredictRequest.sql_text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addition_json_string', full_name='OracleSQLPredict.OracleSQLPredictRequest.addition_json_string', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=234,
)


_ORACLESQLPREDICTRESPONSE = _descriptor.Descriptor(
  name='OracleSQLPredictResponse',
  full_name='OracleSQLPredict.OracleSQLPredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpc_sequence', full_name='OracleSQLPredict.OracleSQLPredictResponse.rpc_sequence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ai_result', full_name='OracleSQLPredict.OracleSQLPredictResponse.ai_result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ai_recommend', full_name='OracleSQLPredict.OracleSQLPredictResponse.ai_recommend', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='OracleSQLPredict.OracleSQLPredictResponse.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addition_json_string', full_name='OracleSQLPredict.OracleSQLPredictResponse.addition_json_string', index=4,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=373,
)

DESCRIPTOR.message_types_by_name['OracleSQLPredictRequest'] = _ORACLESQLPREDICTREQUEST
DESCRIPTOR.message_types_by_name['OracleSQLPredictResponse'] = _ORACLESQLPREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OracleSQLPredictRequest = _reflection.GeneratedProtocolMessageType('OracleSQLPredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _ORACLESQLPREDICTREQUEST,
  __module__ = 'oracle_sql_predict_pb2'
  # @@protoc_insertion_point(class_scope:OracleSQLPredict.OracleSQLPredictRequest)
  ))
_sym_db.RegisterMessage(OracleSQLPredictRequest)

OracleSQLPredictResponse = _reflection.GeneratedProtocolMessageType('OracleSQLPredictResponse', (_message.Message,), dict(
  DESCRIPTOR = _ORACLESQLPREDICTRESPONSE,
  __module__ = 'oracle_sql_predict_pb2'
  # @@protoc_insertion_point(class_scope:OracleSQLPredict.OracleSQLPredictResponse)
  ))
_sym_db.RegisterMessage(OracleSQLPredictResponse)



_ORACLESQLPREDICTREQUESTER = _descriptor.ServiceDescriptor(
  name='OracleSQLPredictRequester',
  full_name='OracleSQLPredict.OracleSQLPredictRequester',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=376,
  serialized_end=506,
  methods=[
  _descriptor.MethodDescriptor(
    name='SQLPredict',
    full_name='OracleSQLPredict.OracleSQLPredictRequester.SQLPredict',
    index=0,
    containing_service=None,
    input_type=_ORACLESQLPREDICTREQUEST,
    output_type=_ORACLESQLPREDICTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORACLESQLPREDICTREQUESTER)

DESCRIPTOR.services_by_name['OracleSQLPredictRequester'] = _ORACLESQLPREDICTREQUESTER

# @@protoc_insertion_point(module_scope)
