# Generated by Django 2.2.2 on 2019-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiSrProfileManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userid', models.CharField(max_length=128)),
                ('tenant', models.CharField(max_length=128)),
                ('profile_name', models.CharField(max_length=128)),
                ('db_type', models.CharField(max_length=128)),
                ('host', models.CharField(blank=True, max_length=256, null=True)),
                ('port', models.CharField(blank=True, max_length=256, null=True)),
                ('instance_name', models.CharField(blank=True, max_length=256, null=True)),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('passwd', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'ai_sr_profile_manage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AiSrSchemaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userid', models.CharField(max_length=128)),
                ('tenant', models.CharField(max_length=128)),
                ('schema_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'ai_sr_schema_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AiSrSqlDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.CharField(max_length=128, unique=True)),
                ('tenant_code', models.CharField(max_length=128)),
                ('db_type', models.CharField(max_length=128)),
                ('db_conn_url', models.CharField(blank=True, max_length=512, null=True)),
                ('schema_name', models.CharField(max_length=128)),
                ('sql_text', models.TextField()),
                ('statement', models.CharField(blank=True, max_length=128, null=True)),
                ('dynamic_mosaicking', models.CharField(blank=True, max_length=128, null=True)),
                ('table_names', models.CharField(blank=True, max_length=4096, null=True)),
                ('plan_text', models.TextField(blank=True, null=True)),
                ('plan_raw', models.TextField(blank=True, null=True)),
                ('sql_data', models.TextField(blank=True, null=True)),
                ('ai_result', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('ai_error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('ai_error_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'ai_sr_sql_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AiSrTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(blank=True, max_length=128, null=True)),
                ('userid', models.CharField(blank=True, max_length=128, null=True)),
                ('task_id', models.CharField(default='a7ef28fa-18b6-4deb-82f8-26dd1c216741', max_length=128)),
                ('task_type', models.CharField(max_length=128)),
                ('task_status', models.CharField(max_length=128)),
                ('task_message', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('sql_total', models.CharField(blank=True, max_length=128, null=True)),
                ('sql_need_optimize', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'ai_sr_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AiSrTaskSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=128)),
                ('task_type', models.CharField(max_length=128)),
                ('sql_id_alias', models.CharField(max_length=128)),
                ('sql_sequence', models.CharField(max_length=128, unique=True)),
                ('db_type', models.CharField(max_length=128)),
                ('schema_name', models.CharField(max_length=128)),
                ('sql_text', models.TextField()),
                ('ref_id', models.CharField(blank=True, max_length=128, null=True)),
                ('ai_result', models.CharField(blank=True, max_length=128, null=True)),
                ('ai_recommend', models.TextField(blank=True, null=True)),
                ('ai_message', models.TextField(blank=True, null=True)),
                ('ai_error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('ai_error_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'ai_sr_task_sql',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AiSrTenantSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userid', models.CharField(max_length=128)),
                ('tenant', models.CharField(max_length=128)),
                ('profile_name', models.CharField(max_length=128)),
                ('db_type', models.CharField(max_length=128)),
                ('schema_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'ai_sr_tenant_schema',
                'managed': False,
            },
        ),
    ]
